#! /bin/sh

echo Usage: proxborg-restore-latest REPO NEW_VM_ID

export BORG_REPO=$1
NEW_VMID=$2
# BORG_PASSPHRASE=your_repo_passphrase 
ARCHIVES=`borg list`
echo "Archives:"
echo "$ARCHIVES"
LATEST=`echo "$ARCHIVES" | tail -1 | cut -f1 -d' '`
echo "Auto-choosing last archive: $LATEST"
echo "Press any key to continue"
read -n 1
./proxborg-restore $NEW_VMID "$LATEST"
